<?php

return [
    'automation_actor_user_id' => env('CARE_AUTOMATION_ACTOR_USER_ID'),
    'scheduler_automation_actor_user_id' => env(
        'SCHEDULER_AUTOMATION_ACTOR_USER_ID',
        env('CARE_AUTOMATION_ACTOR_USER_ID'),
    ),
    'scheduler_automation_actor_required_role' => env('SCHEDULER_AUTOMATION_ACTOR_REQUIRED_ROLE', 'AutomationService'),
    'medication_reminder_offset_days' => (int) env('CARE_MEDICATION_OFFSET_DAYS', 0),
    'post_treatment_follow_up_offset_days' => (int) env('CARE_FOLLOW_UP_OFFSET_DAYS', 3),
    'recall_default_offset_days' => (int) env('CARE_RECALL_DEFAULT_OFFSET_DAYS', 180),
    'no_show_recovery_delay_hours' => (int) env('CARE_NO_SHOW_RECOVERY_DELAY_HOURS', 2),
    'plan_follow_up_delay_days' => (int) env('CARE_PLAN_FOLLOW_UP_DELAY_DAYS', 2),
    'invoice_aging_reminder_delay_days' => (int) env('CARE_INVOICE_AGING_REMINDER_DELAY_DAYS', 1),
    'invoice_aging_reminder_min_interval_hours' => (int) env('CARE_INVOICE_AGING_REMINDER_MIN_INTERVAL_HOURS', 24),
    'report_snapshot_sla_hours' => (int) env('CARE_REPORT_SNAPSHOT_SLA_HOURS', 6),
    'report_snapshot_stale_after_hours' => (int) env('CARE_REPORT_SNAPSHOT_STALE_AFTER_HOURS', 24),
    'scheduler_command_timeout_seconds' => (int) env('CARE_SCHEDULER_COMMAND_TIMEOUT_SECONDS', 180),
    'scheduler_command_max_attempts' => (int) env('CARE_SCHEDULER_COMMAND_MAX_ATTEMPTS', 2),
    'scheduler_command_retry_delay_seconds' => (int) env('CARE_SCHEDULER_COMMAND_RETRY_DELAY_SECONDS', 15),
    'scheduler_command_alert_after_seconds' => (int) env('CARE_SCHEDULER_COMMAND_ALERT_AFTER_SECONDS', 120),
    'sync_dead_letter_alert_enabled' => (bool) env('CARE_SYNC_DEAD_LETTER_ALERT_ENABLED', true),
    'sync_dead_letter_alert_threshold' => (int) env('CARE_SYNC_DEAD_LETTER_ALERT_THRESHOLD', 1),
    'observability_window_hours' => (int) env('CARE_OBSERVABILITY_WINDOW_HOURS', 24),
    'observability_dead_letter_error_budget' => (int) env('CARE_OBSERVABILITY_DEAD_LETTER_ERROR_BUDGET', 0),
    'observability_retryable_failure_error_budget' => (int) env('CARE_OBSERVABILITY_RETRYABLE_FAILURE_ERROR_BUDGET', 5),
    'observability_open_kpi_alert_error_budget' => (int) env('CARE_OBSERVABILITY_OPEN_KPI_ALERT_ERROR_BUDGET', 5),
    'observability_snapshot_sla_error_budget' => (int) env('CARE_OBSERVABILITY_SNAPSHOT_SLA_ERROR_BUDGET', 0),
    'observability_recent_automation_failure_error_budget' => (int) env('CARE_OBSERVABILITY_RECENT_AUTOMATION_FAILURE_ERROR_BUDGET', 20),
    'security_mfa_required_roles' => explode(',', (string) env('CARE_SECURITY_MFA_REQUIRED_ROLES', 'Admin,Manager')),
    'security_allow_bootstrap_without_mfa' => (bool) env(
        'CARE_SECURITY_ALLOW_BOOTSTRAP_WITHOUT_MFA',
        env('APP_ENV', 'production') !== 'production',
    ),
    'security_seed_demo_mfa' => (bool) env('CARE_SECURITY_SEED_DEMO_MFA', false),
    'security_session_idle_timeout_minutes' => (int) env('CARE_SECURITY_SESSION_IDLE_TIMEOUT_MINUTES', 30),
    'security_login_max_attempts' => (int) env('CARE_SECURITY_LOGIN_MAX_ATTEMPTS', 5),
    'security_login_lockout_minutes' => (int) env('CARE_SECURITY_LOGIN_LOCKOUT_MINUTES', 15),
    'emr_media_storage_disk' => env('CARE_EMR_MEDIA_STORAGE_DISK', 'local'),
    'emr_media_signed_url_ttl_minutes' => (int) env('CARE_EMR_MEDIA_SIGNED_URL_TTL_MINUTES', 5),
    'emr_media_retention_enabled' => (bool) env('CARE_EMR_MEDIA_RETENTION_ENABLED', true),
    'emr_media_retention_days' => [
        'clinical_legal' => (int) env('CARE_EMR_MEDIA_RETENTION_DAYS_CLINICAL_LEGAL', 0),
        'clinical_operational' => (int) env('CARE_EMR_MEDIA_RETENTION_DAYS_CLINICAL_OPERATIONAL', 365),
        'temporary' => (int) env('CARE_EMR_MEDIA_RETENTION_DAYS_TEMPORARY', 30),
    ],
    'emr_dicom_enabled' => (bool) env('CARE_EMR_DICOM_ENABLED', false),
    'emr_dicom_base_url' => env('CARE_EMR_DICOM_BASE_URL', ''),
    'emr_dicom_facility_code' => env('CARE_EMR_DICOM_FACILITY_CODE', ''),
    'emr_dicom_timeout_seconds' => (int) env('CARE_EMR_DICOM_TIMEOUT_SECONDS', 10),
    'emr_dicom_auth_token' => env('CARE_EMR_DICOM_AUTH_TOKEN', ''),
    'security_enforce_in_tests' => (bool) env('CARE_SECURITY_ENFORCE_IN_TESTS', false),
    'ops_alert_runbook' => [
        'backup_health' => [
            'owner_role' => 'Admin',
            'threshold' => 'latest_backup_age_hours<=26',
            'runbook' => 'Backup health gate + manual verification',
        ],
        'restore_drill' => [
            'owner_role' => 'Admin',
            'threshold' => 'restore_drill=pass_daily',
            'runbook' => 'Restore drill command and checksum verification',
        ],
        'scheduler_runtime' => [
            'owner_role' => 'AutomationService',
            'threshold' => 'runtime_seconds<=alert_after_seconds',
            'runbook' => 'Retry policy + alert on failure/sla breach',
        ],
        'google_calendar_dead_letter' => [
            'owner_role' => 'AutomationService',
            'threshold' => 'dead_backlog<=sync.dead_letter_alert_threshold',
            'runbook' => 'Investigate Google outbox dead-letter, replay/requeue and verify provider availability.',
        ],
        'emr_dead_letter' => [
            'owner_role' => 'AutomationService',
            'threshold' => 'dead_backlog<=sync.dead_letter_alert_threshold',
            'runbook' => 'Investigate EMR outbox dead-letter, reconcile payload and rerun EMR sync safely.',
        ],
        'zns_automation_dead_letter' => [
            'owner_role' => 'AutomationService',
            'threshold' => 'dead_backlog<=sync.dead_letter_alert_threshold',
            'runbook' => 'Investigate ZNS dead-letter events, verify template/phone/provider, then replay eligible events.',
        ],
        'cross_module_observability' => [
            'owner_role' => 'AutomationService',
            'threshold' => 'all_metrics<=error_budget',
            'runbook' => 'Run observability health gate, burn-rate triage, and incident handoff by module owner.',
        ],
        'kpi_snapshot_sla' => [
            'owner_role' => 'Manager',
            'threshold' => 'snapshot_sla_status=on_time',
            'runbook' => 'Snapshot SLA check + ownership follow-up',
        ],
        'security_login_lockout' => [
            'owner_role' => 'Admin',
            'threshold' => 'failed_login_attempts<=security.login_max_attempts',
            'runbook' => 'Investigate suspicious login attempts and unblock workflow',
        ],
    ],
];
